language: java
jdk:
  - oraclejdk8

script:
  mvn clean verify

before_install:
[
   cd patientmanager]
 

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
    rvm: 2.0.0
 
