language: java
jdk:
  - oraclejdk8

script:
  mvn clean verify

before_install:
  - cd patientmanager
  
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
