language: java
jdk:
  - oraclejdk8

script:
  mvn clean verify

before_install:
  - cd patientmanager
  
  before_deploy:
  - "mvn -DskipTests package"
  - export FOO=$(ls target/foo-version-*.jar)

deploy:
  provider: releases
  api_key:
    secure: yep
  file: "${FOO}"
  
 
