language: java
jdk:
  - oraclejdk8

script:
  mvn clean verify

before_install:
   "cd patientmanager"
  
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  
  on:
    branch: release
    

